# Generated by Django 5.2 on 2025-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Cancelled', 'Cancelled')], default='Placed', max_length=10),
        ),
    ]
